import { Header } from "@/components/interface/header";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/providers/providers";
// import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: "7OnSexy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className="h-full">
      <body className="bg-[#f3f3f3] h-full">
        <Providers>
          <div className="h-full flex flex-col ">
            <Header />
            <Toaster />
            <main className="max-w-[1930px] w-full mx-auto flex-1 flex flex-col my-4">
              {children}
            </main>
          </div>
          {/* <Analytics /> */}
        </Providers>
      </body>
    </html>
  );
}
